# Generated by Django 5.1.1 on 2024-10-16 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="section",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.section",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="subcategories",
            field=models.ManyToManyField(
                related_name="products", to="products.subcategory"
            ),
        ),
    ]
